<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-06-25 10:05:20              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 namespace App\Console\Commands; use App\Models\Customer; use App\Models\CustomerCoordinate; use Illuminate\Console\Command; class GenerateCustomerCoordinates extends Command { protected $signature = 'customers:generate-coordinates
                            {--base-lat=-8.145000 : Base latitude}
                            {--base-lng=112.285000 : Base longitude}
                            {--spacing=0.0025 : Spacing between customers (degrees)}
                            {--cols=4 : Number of columns in grid}'; protected $description = 'Generate dummy coordinates for customers in Desa Jatitengah, Selopuro, Blitar'; public function handle() { goto gyLxV; ouhJ9: $MDZ0z->start(); goto LhNIq; DgNnF: $HpIbc = 0; goto qq11S; RpRiv: $this->line("  Latitude:  {$P1gbP} to " . round($P1gbP + $JEn97 * $kbCzM, 4)); goto xTzLI; qq11S: $bs52g = 0; goto IRTjQ; xxzNe: $MDZ0z->finish(); goto Vdlq7; TDEjE: $this->table(['Metric', 'Count'], [['Created', $HpIbc], ['Updated', $bs52g], ['Total', $DNt6O->count()]]); goto Ygmqx; Ygmqx: $this->info("Coordinate range:"); goto RpRiv; mkHLd: $this->info("Generating coordinates for {$DNt6O->count()} customers..."); goto qXS04; aYQ3R: $a5EOv = 0; goto DgNnF; ZWx2x: $r8HAk = (int) $this->option('cols'); goto T9emV; LWnPW: $this->info("Spacing: ~" . round($kbCzM * 111, 1) . " km (~" . round($kbCzM * 111000, 0) . " meters)"); goto LDyb7; qXS04: $this->info("Location: Desa Jatitengah, Selopuro, Blitar"); goto LWnPW; xTzLI: $this->line("  Longitude: {$Vbt7X} to " . round($Vbt7X + $r8HAk * $kbCzM, 4)); goto cKYi8; tCldc: if ($DNt6O->isEmpty()) { $this->error('No customers found.'); return 1; } goto mkHLd; cKYi8: return 0; goto V55Hv; EoKf_: $this->info("✅ Coordinates generated successfully!"); goto TDEjE; gyLxV: $P1gbP = (float) $this->option('base-lat'); goto I1oe2; dfqWO: $kbCzM = (float) $this->option('spacing'); goto ZWx2x; IRTjQ: $MDZ0z = $this->output->createProgressBar($DNt6O->count()); goto ouhJ9; T9emV: $DNt6O = Customer::all(); goto tCldc; LDyb7: $JEn97 = 0; goto aYQ3R; LhNIq: foreach ($DNt6O as $nwTPs) { goto fXoY4; AHPE7: $OH4XC += mt_rand(-5, 5) / 10000; goto uUsB0; YwOhr: if ($a5EOv >= $r8HAk) { $a5EOv = 0; $JEn97++; } goto lL5dQ; R5MO5: CustomerCoordinate::updateOrCreate(['customer_id' => $nwTPs->id], ['tenant_id' => $nwTPs->tenant_id, 'latitude' => $eiy4X, 'longitude' => $OH4XC]); goto UUEho; PFW6a: $a5EOv++; goto YwOhr; UUEho: if ($PLdUX) { $bs52g++; } else { $HpIbc++; } goto PFW6a; w0mEn: $PLdUX = CustomerCoordinate::where('customer_id', $nwTPs->id)->exists(); goto R5MO5; fXoY4: $eiy4X = $P1gbP + $JEn97 * $kbCzM; goto NDnG3; uUsB0: $eiy4X = round($eiy4X, 7); goto Tpx1v; lL5dQ: $MDZ0z->advance(); goto PICAC; Tpx1v: $OH4XC = round($OH4XC, 7); goto w0mEn; Ds_Eo: $eiy4X += mt_rand(-5, 5) / 10000; goto AHPE7; NDnG3: $OH4XC = $Vbt7X + $a5EOv * $kbCzM; goto Ds_Eo; PICAC: } goto xxzNe; I1oe2: $Vbt7X = (float) $this->option('base-lng'); goto dfqWO; Vdlq7: $this->newLine(2); goto EoKf_; V55Hv: } }