<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-06-27 01:21:30              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 namespace App\Console\Commands; use App\Models\Customer; use App\Models\CustomerCoordinate; use Illuminate\Console\Command; class GenerateCustomerCoordinates extends Command { protected $signature = 'customers:generate-coordinates
                            {--base-lat=-8.145000 : Base latitude}
                            {--base-lng=112.285000 : Base longitude}
                            {--spacing=0.0025 : Spacing between customers (degrees)}
                            {--cols=4 : Number of columns in grid}'; protected $description = 'Generate dummy coordinates for customers in Desa Jatitengah, Selopuro, Blitar'; public function handle() { goto AM5Tb; W2vju: $doncG = 0; goto xXQRZ; dTS9I: $this->info("✅ Coordinates generated successfully!"); goto h5I3u; tlp90: $VnVOh = 0; goto TkSyg; uE5j9: $this->info("Spacing: ~" . round($TcCm4 * 111, 1) . " km (~" . round($TcCm4 * 111000, 0) . " meters)"); goto fJiDz; yZWz_: $JVPvD->start(); goto TVdYm; h5I3u: $this->table(['Metric', 'Count'], [['Created', $uxPAg], ['Updated', $VnVOh], ['Total', $QCHX2->count()]]); goto a_u8Y; nM7B1: $TcCm4 = (float) $this->option('spacing'); goto cPTqC; TVdYm: foreach ($QCHX2 as $RX5oA) { goto YyJlL; NQymu: $W__2c = $YPIyP + $doncG * $TcCm4; goto h8ZW3; ck9W5: $UkqiL = round($UkqiL, 7); goto JtPiP; qCwwy: $W__2c += mt_rand(-5, 5) / 10000; goto ck9W5; h8ZW3: $UkqiL += mt_rand(-5, 5) / 10000; goto qCwwy; EQVvM: $vgI3e = CustomerCoordinate::where('customer_id', $RX5oA->id)->exists(); goto B4SFU; B4SFU: CustomerCoordinate::updateOrCreate(['customer_id' => $RX5oA->id], ['tenant_id' => $RX5oA->tenant_id, 'latitude' => $UkqiL, 'longitude' => $W__2c]); goto YEo7B; HWdhc: if ($doncG >= $TSxsQ) { $doncG = 0; $PVytA++; } goto ybg7L; YEo7B: if ($vgI3e) { $VnVOh++; } else { $uxPAg++; } goto VygbN; VygbN: $doncG++; goto HWdhc; ybg7L: $JVPvD->advance(); goto W2gRT; YyJlL: $UkqiL = $BXobp + $PVytA * $TcCm4; goto NQymu; JtPiP: $W__2c = round($W__2c, 7); goto EQVvM; W2gRT: } goto Hm3PU; owZeV: $this->info("Location: Desa Jatitengah, Selopuro, Blitar"); goto uE5j9; xXQRZ: $uxPAg = 0; goto tlp90; a_u8Y: $this->info("Coordinate range:"); goto KOhYf; qrBlb: $this->line("  Longitude: {$YPIyP} to " . round($YPIyP + $TSxsQ * $TcCm4, 4)); goto bJEQM; fJiDz: $PVytA = 0; goto W2vju; QbeTf: $YPIyP = (float) $this->option('base-lng'); goto nM7B1; cPTqC: $TSxsQ = (int) $this->option('cols'); goto WCrCS; JC_hy: if ($QCHX2->isEmpty()) { $this->error('No customers found.'); return 1; } goto mP5nR; mP5nR: $this->info("Generating coordinates for {$QCHX2->count()} customers..."); goto owZeV; Hm3PU: $JVPvD->finish(); goto jBCK5; KOhYf: $this->line("  Latitude:  {$BXobp} to " . round($BXobp + $PVytA * $TcCm4, 4)); goto qrBlb; WCrCS: $QCHX2 = Customer::all(); goto JC_hy; AM5Tb: $BXobp = (float) $this->option('base-lat'); goto QbeTf; bJEQM: return 0; goto Y9zi0; TkSyg: $JVPvD = $this->output->createProgressBar($QCHX2->count()); goto yZWz_; jBCK5: $this->newLine(2); goto dTS9I; Y9zi0: } }
