<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-06-25 10:49:50              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 namespace App\Console\Commands; use App\Models\Customer; use App\Models\CustomerCoordinate; use Illuminate\Console\Command; class GenerateCustomerCoordinates extends Command { protected $signature = 'customers:generate-coordinates
                            {--base-lat=-8.145000 : Base latitude}
                            {--base-lng=112.285000 : Base longitude}
                            {--spacing=0.0025 : Spacing between customers (degrees)}
                            {--cols=4 : Number of columns in grid}'; protected $description = 'Generate dummy coordinates for customers in Desa Jatitengah, Selopuro, Blitar'; public function handle() { goto a3COG; QK2i4: $H3pvf = 0; goto G4ltE; a3COG: $XB36n = (float) $this->option('base-lat'); goto TkEdS; TkEdS: $bfo3U = (float) $this->option('base-lng'); goto eJ43q; c2dYb: return 0; goto zYFwc; G4ltE: $yXaqK = 0; goto zCug8; HSBBj: $X2SHt->finish(); goto qKh_o; ZpZio: $this->info("Location: Desa Jatitengah, Selopuro, Blitar"); goto FCjsk; XpMP2: $B8lux = Customer::all(); goto aQqhh; kYNLx: $this->line("  Longitude: {$bfo3U} to " . round($bfo3U + $igK4E * $VS3lO, 4)); goto c2dYb; RH9T3: $this->table(['Metric', 'Count'], [['Created', $h1Fiw], ['Updated', $xeoWe], ['Total', $B8lux->count()]]); goto xE019; Oh146: foreach ($B8lux as $ygIPj) { goto Xprck; I6opT: $FeeaK += mt_rand(-5, 5) / 10000; goto HTUA1; d1F0f: $UQn_9 = $bfo3U + $yXaqK * $VS3lO; goto I6opT; P9SmV: $X2SHt->advance(); goto IL7uW; qc13B: CustomerCoordinate::updateOrCreate(['customer_id' => $ygIPj->id], ['tenant_id' => $ygIPj->tenant_id, 'latitude' => $FeeaK, 'longitude' => $UQn_9]); goto Hf_8G; Dhqbu: if ($yXaqK >= $igK4E) { $yXaqK = 0; $H3pvf++; } goto P9SmV; rKwyz: $dvaec = CustomerCoordinate::where('customer_id', $ygIPj->id)->exists(); goto qc13B; Pj5sH: $yXaqK++; goto Dhqbu; Xprck: $FeeaK = $XB36n + $H3pvf * $VS3lO; goto d1F0f; Hf_8G: if ($dvaec) { $xeoWe++; } else { $h1Fiw++; } goto Pj5sH; bg9QI: $FeeaK = round($FeeaK, 7); goto nsTOz; nsTOz: $UQn_9 = round($UQn_9, 7); goto rKwyz; HTUA1: $UQn_9 += mt_rand(-5, 5) / 10000; goto bg9QI; IL7uW: } goto HSBBj; yeZy6: $this->info("✅ Coordinates generated successfully!"); goto RH9T3; qKh_o: $this->newLine(2); goto yeZy6; Fdo4R: $igK4E = (int) $this->option('cols'); goto XpMP2; FCjsk: $this->info("Spacing: ~" . round($VS3lO * 111, 1) . " km (~" . round($VS3lO * 111000, 0) . " meters)"); goto QK2i4; haXJB: $X2SHt->start(); goto Oh146; aQqhh: if ($B8lux->isEmpty()) { $this->error('No customers found.'); return 1; } goto JTLtV; JTLtV: $this->info("Generating coordinates for {$B8lux->count()} customers..."); goto ZpZio; xE019: $this->info("Coordinate range:"); goto KTe0k; zCug8: $h1Fiw = 0; goto jWBKD; eJ43q: $VS3lO = (float) $this->option('spacing'); goto Fdo4R; M647X: $X2SHt = $this->output->createProgressBar($B8lux->count()); goto haXJB; jWBKD: $xeoWe = 0; goto M647X; KTe0k: $this->line("  Latitude:  {$XB36n} to " . round($XB36n + $H3pvf * $VS3lO, 4)); goto kYNLx; zYFwc: } }
